global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "openclaw-gateway"
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: ["http://docker1.fasanvejen.local:18789/health"]
    static_configs:
        - targets: ["blackbox:9115"]
  - job_name: "openclaw-control-ui"
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: ["http://docker1.fasanvejen.local:18791/"]
    static_configs:
      - targets: ["blackbox:9115"]
  - job_name: "blackbox"
  static_configs:
    - targets: ["blackbox:9115"]
