apiVersion: 1

policies:
  - orgId: 1
    receiver: 'email'
    group_by:
      - alertname
    mute_timings: []
    routes:
      - receiver: 'email'
        object_matchers:
          - ['severity', '=', 'critical']
